## Pandas In Class

# Import the necessary libraries

In [2]:
import pandas as pd

# Load the Data

In [5]:
employee_df = pd.read_csv('EMPLOYEE.csv')
department_df = pd.read_csv('DEPARTMENT.csv')

# Inspect the data

In [10]:
employee_df.head()

,FNAME,LNAME,SSN,BDATE,ADDRESS,SALARY,SUPERSSN,DNO
0,James,Borg,888665555,10-Nov-27,"450 Stone, Houston, TX",55000.0,NaN,1
1,Jennifer,Wallace,987654321,20-Jun-31,"291 Berry, Bellaire, TX",43000.0,888665555.0,4
2,Alicia,Zelaya,999887777,19-Jul-58,"3321 Castle, Spring, TX",25000.0,987654321.0,4
3,Ahmad,Jabbar,987987987,29-Mar-59,"980 Dallas, Houston, TX",25000.0,987654321.0,4
4,Joyce,English,453453453,31-Jul-62,"5631 Rice Oak, Houston, TX",25000.0,333445555.0,5

In [11]:
department_df.head()

            DNAME  DNUMBER     MGRSSN MGRSTARTDATE
0    Headquarters        1  888665555    19-JUN-71
1  Administration        4  987654321    01-JAN-85
2        Research        5  333445555    22-MAY-78
3        Software        6  111111100    15-MAY-99
4        Hardware        7  444444400    15-MAY-98

In [12]:
employee_df.describe()

                SSN        SALARY      SUPERSSN        DNO
count  4.000000e+01     37.000000  3.300000e+01  40.000000
mean   5.027025e+08  50148.648649  5.177669e+08   6.575000
std    2.585463e+08  19951.978760  2.556414e+08   1.550641
min    1.111111e+08  25000.000000  1.111111e+08   1.000000
25%    2.222222e+08  36000.000000  3.333333e+08   6.000000
50%    5.555555e+08  44000.000000  6.666666e+08   7.000000
75%    6.666666e+08  61000.000000  6.666666e+08   8.000000
max    9.998878e+08  96000.000000  9.876543e+08   8.000000

In [13]:
department_df.describe()

        DNUMBER        MGRSSN
count  6.000000  6.000000e+00
mean   5.166667  5.534794e+08
std    2.483277  3.337230e+08
min    1.000000  1.111111e+08
25%    4.250000  3.611953e+08
50%    5.500000  5.000000e+08
75%    6.750000  8.053880e+08
max    8.000000  9.876543e+08

# Data Cleaning

In [ ]:
#check for missing values 
employee_df.isnull().sum()
department_df.isnull().sum()

np.True_

In [ ]:
#drop na values
employee_df.dropna()
department_df.dropna()

In [ ]:
#ensure all DNO in employee dataframe matches with DNUMBER in department dataframe
employee_df["DNO"].isin(department_df["DNUMBER"]).all()

# Data Manipulation

In [24]:
#get employee names with salaries over 40000

salary_row = employee_df[employee_df['SALARY']>40000]
salary_row[['FNAME', 'LNAME']]

       FNAME    LNAME
0      James     Borg
1   Jennifer  Wallace
8      Jared    James
9       Brad   Knight
10      Jeff    Chase
11       Jon    Jones
13      John    James
14   Nandita     Ball
15       Kim    Grace
16       Sam  Snedden
17      Alec     Best
18    Bonnie     Bays
19     Jenny      Vos
20       Tom    Brand
21      Andy     Vile
22      Josh     Zell
23      Evan   Wallis
24      Alex    Freed
25     Chris   Carter
26       Bob   Bender
28      Kate     King
29      Lyle   Leslie
39       Ray     King

In [25]:
#get employee names whose supervisor is 666666602

supervisor_row = employee_df[employee_df['SUPERSSN'] == 666666602]
supervisor_row[['FNAME', 'LNAME']]

     FNAME   LNAME
33  Gerald   Small
34  Arnold    Head
35   Helga  Pataki

# Merging the data

In [27]:
#merge dfs on DNO and DNUMBER
merge_df = pd.merge(employee_df, department_df, left_on='DNO', right_on='DNUMBER')
merge_df.head()

,FNAME,LNAME,SSN,BDATE,ADDRESS,SALARY,SUPERSSN,DNO,DNAME,DNUMBER,MGRSSN,MGRSTARTDATE
0,James,Borg,888665555,10-Nov-27,"450 Stone, Houston, TX",55000.0,NaN,1,Headquarters,1,888665555,19-JUN-71
1,Jennifer,Wallace,987654321,20-Jun-31,"291 Berry, Bellaire, TX",43000.0,888665555.0,4,Administration,4,987654321,01-JAN-85
2,Alicia,Zelaya,999887777,19-Jul-58,"3321 Castle, Spring, TX",25000.0,987654321.0,4,Administration,4,987654321,01-JAN-85
3,Ahmad,Jabbar,987987987,29-Mar-59,"980 Dallas, Houston, TX",25000.0,987654321.0,4,Administration,4,987654321,01-JAN-85
4,Joyce,English,453453453,31-Jul-62,"5631 Rice Oak, Houston, TX",25000.0,333445555.0,5,Research,5,333445555,22-MAY-78

# Filter for the research department

In [31]:
#filter the dataframe
research_df = merge_df[merge_df['DNAME'] == 'Research']

#show employees that are in research department 
print(research_df[['FNAME', 'LNAME']])

      FNAME    LNAME
4     Joyce  English
5  Franklin     Wong
6      John    Smith
7    Ramesh  Narayan